### ISSUE TITLE
Errore Search Filters

### ISSUE THREAD

**Issue by fsacchi74** [RedTurtle/design.plone.policy#29]
Buongiorno,
la chiamata @search-filters va sempre in errore 500.

{
  "message": "'NoneType' object is not iterable",
  "traceback": [
    "File \"/opt/plone/buildout-cache/eggs/cp37m/Zope-4.5.5-py3.7.egg/ZPublisher/WSGIPublisher.py\", line 162, in transaction_pubevents",
    "    yield",
    "",
    "  File \"/opt/plone/buildout-cache/eggs/cp37m/Zope-4.5.5-py3.7.egg/ZPublisher/WSGIPublisher.py\", line 371, in publish_module",
    "    response = _publish(request, new_mod_info)",
    "",
    "  File \"/opt/plone/buildout-cache/eggs/cp37m/Zope-4.5.5-py3.7.egg/ZPublisher/WSGIPublisher.py\", line 274, in publish",
    "    bind=1)",
    "",
    "  File \"/opt/plone/buildout-cache/eggs/cp37m/Zope-4.5.5-py3.7.egg/ZPublisher/mapply.py\", line 85, in mapply",
    "    return debug(object, args, context)",
    "",
    "  File \"/opt/plone/buildout-cache/eggs/cp37m/Zope-4.5.5-py3.7.egg/ZPublisher/WSGIPublisher.py\", line 63, in call_object",
    "    return obj(*args)",
    "",
    "  File \"/opt/plone/buildout-cache/eggs/cp37m/plone.rest-1.6.2-py3.7.egg/plone/rest/service.py\", line 22, in __call__",
    "    return self.render()",
    "",
    "  File \"/opt/plone/buildout-cache/eggs/cp37m/plone.restapi-8.5.0-py3.7.egg/plone/restapi/services/__init__.py\", line 19, in render",
    "    content = self.reply()",
    "",
    "  File \"/opt/plone/buildout-cache/eggs/cp37m/design.plone.policy-2.11.3-py3.7.egg/design/plone/policy/restapi/search_filters/get.py\", line 51, in reply",
    "    for uid in section_settings.get(\"linkUrl\", []):"
  ],
  "type": "TypeError"
}

Volto 13.8.2
Plone 5.2.4
CMF 2.5.0
Zope 4.5.5
Python 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
PIL 6.2.2 (Pillow)

Abbiamo anche aggiornato all'ultima versione dei design.plone.policy,ma non è cambiato nulla.

Grazie
Federica

**Comment by cekk** [comment]
Ciao, credo che tu abbia dei dati con una struttura sbagliata dentro al campo "Sezioni ricerca" nel pannello di controllo.
Quel campo viene popolato da Volto, quindi se magari ci avete messo mano a mano, potrebbe essere cambiato qualcosa.

Per vedere un esempio di struttura dati, puoi anche provare ad installare il prodotto su un sito nuovo, e vedere come sono i default

**Comment by mamico** [comment]
ciao  @fsacchi74 https://github.com/RedTurtle/design.plone.policy/commit/c7ae1a845a5472192e8b963f541788ad982e8355 dovrebbe evitare l'errore che avevi. Ma come diceva @cekk probabilmente i dati che hai nel pannello di controllo potrebbero essere inconsistenti.

**Comment by fsacchi74** [comment]
Buongiorno,
confermo che con le corrette impostazioni nel campo "sezioni ricerca" i filtri 
non vanno in errore.

Grazie
